export type {
  AdminCreateProductDto,
  AdminCreateProductResponseDto,
  AdminDeleteProductResponseDto,
  AdminProductDetailsResponseDto,
  AdminProductsListResponseDto,
  AdminProductsQueryDto,
  AdminUpdateProductDto,
  AdminUpdateProductResponseDto,
  AdminApproveProductRevisionDto,
  AdminApproveProductRevisionResponseDto,
  AdminPendingProductRevisionsListResponseDto,
  AdminPendingProductRevisionsQueryDto,
  AdminProductRevisionDetailsResponseDto,
  AdminRejectProductRevisionDto,
  AdminRejectProductRevisionResponseDto,
  ProductApprovalStatus,
  ProductDto,
  ProductImageDto,
  ProductStatus,
  ProductVariantDto,
  ProductRevisionAction,
  ProductRevisionDto,
  ProductRevisionStatus,
} from "@/types/admin-api.dto";
