"use client";

import { AdminSchemaForm } from "@/features/admin/shared";
import type { AdminFormField } from "@/features/admin/shared";

import {
  recommendationFormSchema,
  type RecommendationFormValues,
} from "../schemas/recommendation-form.schema";
import type { CreateRecommendationRequest } from "../types/recommendation.types";

const fields: AdminFormField<RecommendationFormValues>[] = [
  { key: "userId", label: "User ID", placeholder: "User UUID" },
  {
    key: "targetType",
    label: "Target type",
    options: [
      { label: "Store", value: "store" },
      { label: "Offer", value: "offer" },
      { label: "Coupon", value: "coupon" },
      { label: "Category", value: "category" },
    ],
    type: "select",
  },
  { key: "targetId", label: "Target ID", placeholder: "Target UUID" },
  { key: "score", label: "Score", placeholder: "0.85", type: "number" },
  { key: "reasonCode", label: "Reason code", placeholder: "manual-curation" },
  {
    key: "generatedBy",
    label: "Generated by",
    options: [
      { label: "Manual", value: "manual" },
      { label: "System", value: "system" },
      { label: "Model", value: "model" },
    ],
    type: "select",
  },
  { key: "expiresAt", label: "Expires at", type: "datetime-local" },
  {
    key: "contextJson",
    label: "Context JSON",
    placeholder: '{\"placement\":\"homepage\"}',
    type: "textarea",
  },
];

export function RecommendationForm({
  description,
  isSubmitting,
  onSubmit,
  submitLabel,
  title,
}: {
  description: string;
  isSubmitting?: boolean;
  onSubmit: (payload: CreateRecommendationRequest) => Promise<unknown>;
  submitLabel: string;
  title: string;
}) {
  return (
    <AdminSchemaForm
      description={description}
      fields={fields}
      isSubmitting={isSubmitting}
      onSubmit={onSubmit}
      schema={recommendationFormSchema}
      submitLabel={submitLabel}
      title={title}
    />
  );
}
