import type { ReactNode } from "react";

import { AdminDataTable, type AdminColumn, formatAdminDate } from "@/features/admin/shared";
import type { Recommendation } from "../types/recommendation.types";

const columns: AdminColumn<Recommendation>[] = [
  {
    id: "id",
    header: "ID",
    accessorKey: "id",
  },
  {
    id: "targetType",
    header: "Target Type",
    accessorKey: "targetType",
  },
  {
    id: "generatedBy",
    header: "Generated By",
    accessorKey: "generatedBy",
  },
  {
    id: "createdAt",
    header: "Created",
    cell: (item) => formatAdminDate(item.createdAt),
  },
];

export function RecommendationsTable({
  items,
  renderActions,
}: {
  items: Recommendation[];
  renderActions?: (item: Recommendation) => ReactNode;
}) {
  return (
    <AdminDataTable
      columns={columns}
      data={items}
      rowKey={(item) => String(item.id ?? JSON.stringify(item))}
      renderRowActions={renderActions}
      emptyDescription="The backend has not returned any recommendations yet."
      emptyTitle="No recommendations found"
    />
  );
}
